import Vue from 'vue'
import Button from './src/components/button'
import Icon from './src/components/icon'
import ButtonGroup from './src/components/button-group'
import Input from './src/components/input'
import Row from './src/components/row'
import Col from './src/components/col'
import plugin from './src/assets/plugin'

import Layout from './src/components/layout'
import Header from './src/components/header'
import Content from './src/components/content'
import Sider from './src/components/sider'
import Footer from './src/components/footer'
import Tabs from './src/components/tabs'
import TabsHead from './src/components/tabs-head'
import TabsBody from './src/components/tabs-body'
import TabsPane from './src/components/tabs-pane'
import TabsItem from './src/components/tabs-item'
import Popover from './src/components/popover'
import Collapse from './src/components/collapse'
import CollapseItem from './src/components/collapse-item'
export {Button, ButtonGroup, Icon, Input, Row, Col, plugin, Layout, Header, Content, Sider, Footer, Tabs, TabsHead, TabsBody, TabsPane, TabsItem, Popover, Collapse, CollapseItem}